### ISSUE TITLE
include timestamp in logger output

### ISSUE THREAD

**Issue by martukas** [ess-dmsc/event-formation-unit#109] opened 2018-09-03 05:36 UTC
Messages written to log file should have timestamps. When reviewing multiple hours or days of log messages, it is impossible to contextualize when an observed problem occurred.

**Comment by SkyToGround** [comment] 2018-09-21 11:36
@martukas Can you elaborate? When testing on both OSX and Linux (using the `--log_file` command line argument) I do get timestamps. Example:
```
2018-09-21 13:24:15 (Muspelheim) Info: Starting event processing pipeline2 with main properties:
2018-09-21 13:24:15 (Muspelheim) Info:   Detector:                 ../../modules/Debug/AdcReadout
2018-09-21 13:24:15 (Muspelheim) Info:   Rx UDP Socket:            0.0.0.0:9000
2018-09-21 13:24:15 (Muspelheim) Info:   Minimum required MTU      9000
2018-09-21 13:24:15 (Muspelheim) Info:   Kafka broker:             localhost:9092
```

**Comment by SkyToGround** [comment] 2018-10-31 22:12
Closing, unable to reproduce.

**Closed by SkyToGround** 2018-10-31 22:12 UTC
